# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-31 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterclassiferalgo',
            name='classifier_pickled_data',
            field=models.TextField(),
        ),
    ]
