# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-29 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_stock', '0002_companyname_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyname',
            name='id',
        ),
        migrations.AlterField(
            model_name='companyname',
            name='yahoo_sht',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
