# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-29 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_stock', '0003_auto_20180129_2335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyName',
            new_name='CompanyDetails',
        ),
    ]
