# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-29 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_stock', '0005_auto_20180129_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStocks',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('open', models.DecimalField(decimal_places=6, max_digits=20)),
                ('close', models.DecimalField(decimal_places=6, max_digits=20)),
                ('adj_close', models.DecimalField(decimal_places=6, max_digits=20)),
                ('high', models.DecimalField(decimal_places=6, max_digits=20)),
                ('low', models.DecimalField(decimal_places=6, max_digits=20)),
                ('record_date', models.DateField()),
                ('volume', models.DecimalField(decimal_places=6, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_stock.CompanyDetails')),
            ],
        ),
    ]
